export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_ERROR = 'GET_CURRENT_WEATHER_ERROR';

export const GET_FORECAST = 'GET_FORECAST';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const GET_FORECAST_ERROR = 'GET_FORECAST_ERROR';


export const GET_WEATHER_HISTORY = 'GET_WEATHER_HISTORY';
export const GET_WEATHER_HISTORY_SUCCESS = 'GET_WEATHER_HISTORY_SUCCESS';
export const GET_WEATHER_HISTORY_ERROR = 'GET_WEATHER_HISTORY_ERROR';
